version: '3.8'

services:
  caddy:
    image: caddy
    container_name: caddy
    ports:
      - '${HTTP_PORT}:80'
      - '${HTTPS_PORT}:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/usr/share/caddy/site
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
